workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      # android_signing:
      #   - keystore_reference
      groups:
        #- google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS)
        - veracode
      vars:
        PACKAGE_NAME: "io.codemagic.flutteryaml" # <-- Put your package name here
        PACKAGE_PATH: ".verascan"
        GOOGLE_PLAY_TRACK: "alpha"
        VERACODE_API_KEY_ID: $VID
        VERACODE_API_KEY_SECRET: $VKEY
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter doctor
        script: |
          flutter doctor --verbose
        ignore_failure: true
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Veracode Package
        script:  |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output $PACKAGE_PATH --trust
          ls -lah $PACKAGE_PATH
        ignore_failure: true
      - name: Build AAB with Flutter
        script: |
          # BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
          BUILD_NUMBER=1
          flutter build apk --debug
          # flutter build appbundle --release \
          #   --build-name=1.0.$BUILD_NUMBER \
          #   --build-number=$BUILD_NUMBER \
          #   --android-skip-build-dependency-validation

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: io.codemagic.flutteryaml
      vars:
        APP_ID: 1111111111 # <-- Put your APP ID here
      flutter: stable
      xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Flutter build ipa and automatic versioning
        script: |
          # See the following link about getting the latest App Store or TestFlight version - https://docs.codemagic.io/knowledge-codemagic/build-versioning/#app-store-or-testflight-latest-build-number
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=1 \
            --export-options-plist=/Users/builder/export_options.plist
            # --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_ID") + 1)) \
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

  web-workflow:
    name: Web app workflow
    max_build_duration: 10
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Flutter build webapp
        script: |
          flutter build web --release
          cd build/web
          7z a -r ../web.zip ./*
    artifacts:
      - build/web.zip
      - flutter_drive.log




